version: "3.7"

volumes:
  database:
    driver: local
  pulsardatav:
    driver: local

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - app_network
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network
  pizzly-server:
    image: nangohq/pizzly-server:0.5.2
    container_name: trigger-pizzly-server
    restart: always
    env_file:
      - .docker/pizzly-server.env
    environment:
      - SERVER_HOST=http://localhost
      - SERVER_PORT=3004
      - NODE_ENV=development
      - NANGO_DB_HOST=db
      - NANGO_DB_USER=postgres
      - NANGO_DB_PASSWORD=postgres
      - NANGO_DB_NAME=postgres
    ports:
      - "3004:3004"
    depends_on:
      - db
    networks:
      - app_network
  pulsar:
    image: apachepulsar/pulsar:2.10.2
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - "pulsardatav:/pulsar/data"
    command: bin/pulsar standalone
    container_name: pulsar
    tty: true
    stdin_open: true
    restart: always

networks:
  app_network:
    external: true
