version: "3.7"

volumes:
  database:
    driver: local

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql-docker/data
    networks:
      - app_network
  pizzly-server:
    image: nangohq/pizzly-server
    container_name: pizzly-server
    restart: always
    environment:
      - SERVER_HOST=http://localhost
      - SERVER_PORT=3004
      - NODE_ENV=development
      - PIZZLY_DB_HOST=db
      - PIZZLY_DB_USER=postgres
      - PIZZLY_DB_PASSWORD=postgres
      - PIZZLY_DB_NAME=postgres
    ports:
      - "3004:3004"
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    external: true
