version: "3"

volumes:
  database-data:

networks:
  app_network:
    external: false

services:
  webapp:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
    networks:
      - app_network

  database:
    container_name: database
    image: postgres:latest
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: .env
    networks:
      - app_network
    ports:
      - 5432:5432
