version: "3.7"

volumes:
  pulsardatav:
    driver: local

services:
  pulsar:
    image: apachepulsar/pulsar:2.10.2
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - "pulsardatav:/pulsar/data"
    command: bin/pulsar standalone
    container_name: pulsar
    tty: true
    stdin_open: true
    restart: always
