name: 🚀 Publish Trigger.dev Docker

on:
  push:
    branches:
      - main
      - dev-q22023

permissions:
  id-token: write
  packages: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.18

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: 📥 Download deps
        run: pnpm install --frozen-lockfile

      - name: 📀 Generate Prisma Client
        run: pnpm run generate

      - name: 🔎 Type check
        run: pnpm run typecheck --filter webapp

  publish:
    needs: [typecheck]
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🐳 Docker Build
        run: |
          docker build -t trigger_build_image -f docker/Dockerfile .

      # Push to Public Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        run: |
          docker tag trigger_build_image $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        env:
          REGISTRY: ghcr.io/triggerdogdev
          REPOSITORY: trigger.dev
          IMAGE_TAG: ${{ github.head_ref || github.ref_name }}
